#include "ps4.h"

uint64_t *g_controller;
//uint8_t *g_appIdTag;
uint64_t entry_1, entry_15, entry_16;
int64_t appRet;
//uint8_t appIdTag, test;
//int *test2;
int appId;
uint16_t fw;
uint8_t *kernel_ptr;
uint64_t kernel_base;


void get_controller_app_handle()
{
//-------------------------------------------------------------------------------------------
// seems that g_controller entries are pointers to application entrypoint addresses???
// g_controller is a global array of applications with a corresponding ID, length 16 with entries 8 bytes wide
// entries are generated by generateApplicationId function, 2nd arg is based on checks done to array entries
// getAppId function definition is as follows: int64_t getApplicationById(int appId, uint64_t *globalArrayPtr, int arraySize)

  if (fw == 505)
  {
	  g_controller = (uint64_t *)(&kernel_ptr[0x271DE10]);
	  int64_t (*getApplicationById)(uint64_t,uint64_t*,int) = (void *)(&kernel_ptr[0x5DD860]);
	  entry_1 = g_controller[0];
	  entry_15 = g_controller[14];
	  entry_16 = g_controller[15];
	  appId = *(int *)(entry_1 + 0x4); // this gets us the app ID
	  appRet = getApplicationById(appId, g_controller, 16);
  }
  else if (fw == 900)
  {
	  g_controller = (uint64_t *)(&kernel_ptr[0x26469F0]); // 9.00 0x26469F0
	  int64_t (*getApplicationById)(uint64_t,uint64_t*,int) = (void *)(&kernel_ptr[0x601E80]); // 9.00 0x601E80
	  entry_1 = g_controller[0];
	  entry_15 = g_controller[14];
	  entry_16 = g_controller[15];
	  appId = *(int *)(entry_1 + 0x4); // this gets us the app ID
	  appRet = getApplicationById(appId, g_controller, 16);
  }
  //g_appIdTag = (uint8_t *)(&kernel_ptr[0x26FC072]);
  //int64_t (*generateApplicationId)(int,int) = (void *)(&kernel_ptr[0x5DD240]);
  //appIdTag = *g_appIdTag;
  //appId = generateApplicationId(3, 0); // seems that first arg should be 3, increments appIdTag by 1 everytime it is called
  //test = *(uint8_t *)(entry_1 + 0x18); // returns the value 1
  //test2 = *(int **)(entry_1 + 0x130);
  //test3 = *test2;
}


/**
** SCE_USER_SERVICE_USER_COLOR_BLUE  0
** SCE_USER_SERVICE_USER_COLOR_RED   1
** SCE_USER_SERVICE_USER_COLOR_GREEN 2
** SCE_USER_SERVICE_USER_COLOR_PINK  3
**/

int _main(void)
{
   initKernel();
   initLibc();

   // jailbreak to use system notifications + pad lib
   jailbreak();
   initSysUtil();
   initPad();

   /*SCE_KERNEL_PRIO_FIFO_DEFAULT = 700
   SCE_KERNEL_PRIO_FIFO_HIGHEST = 256
   SCE_KERNEL_PRIO_FIFO_LOWEST = 767*/
   
   char buffer[1024];
   int ret;

   fw = get_firmware();
   kernel_base = get_kernel_base();
   kernel_ptr = (uint8_t*)kernel_base;
   
   kexec(&get_controller_app_handle, NULL);

   ret = scePadSetUserColor(appId, 2); // returns 0x803B0003 (SCE_HID_ERROR_DEVICE_NOT_FOUND) if invalid appId

   sprintf(buffer, "ret = 0x%x\n\n\n", ret);
   sceSysUtilSendSystemNotificationWithText(0x81, buffer);
   
   sprintf(buffer, "appId = 0x%x\n\n\n", appId);
   sceSysUtilSendSystemNotificationWithText(0x81, buffer);

   sprintf(buffer, "appRet = 0x%x\n\n\n", appRet);
   sceSysUtilSendSystemNotificationWithText(0x81, buffer);

   return 0;
}